### ISSUE TITLE
Error. Socket doesn't exit. Is daemon running?

### ISSUE THREAD

**Issue by creotiv** [rnd-ash/razer-laptop-control#54]
Installed driver and client, rebooted, tried razer-cli, and got "Error. Socket doesn't exit. Is daemon running?"

**Comment by creotiv** [comment]
I have Razer Blade Advanced 2019, and seems the problem that DKMS driver doesnt find any devices

```
creotiv@creotiv:/sys/module/razercontrol/drivers/hid:Razer laptop System control driver$ ls
bind  module  new_id  uevent  unbind

```

**Comment by phelps-sg** [comment]
Same problem on Ubuntu 20.04.2 kernel 5.8.0-41 with Blade 15 Base 2020 edition

**Comment by QuiiBz** [comment]
Same problem here w/ Razer blade 15 Base 2020. The daemon is running, but looks like it can't find `sysfs`:
```
sudo systemctl status razerdaemon.service
* razerdaemon.service - Razer laptop control daemon
     Loaded: loaded (/etc/systemd/system/razerdaemon.service; enabled; vendor preset: dis>
     Active: active (running) since Thu 2021-02-04 14:29:42 CET; 13s ago
   Main PID: 21084 (daemon)
      Tasks: 1 (limit: 19023)
     Memory: 200.0K
     CGroup: /system.slice/razerdaemon.service
             `-21084 /usr/share/razercontrol/daemon

Feb 04 14:29:46 arch daemon[21084]: Waiting for sysfs to be ready
Feb 04 14:29:47 arch daemon[21084]: Waiting for sysfs to be ready
Feb 04 14:29:48 arch daemon[21084]: Waiting for sysfs to be ready
Feb 04 14:29:49 arch daemon[21084]: Waiting for sysfs to be ready
Feb 04 14:29:50 arch daemon[21084]: Waiting for sysfs to be ready
Feb 04 14:29:51 arch daemon[21084]: Waiting for sysfs to be ready
Feb 04 14:29:52 arch daemon[21084]: Waiting for sysfs to be ready
Feb 04 14:29:53 arch daemon[21084]: Waiting for sysfs to be ready
Feb 04 14:29:54 arch daemon[21084]: Waiting for sysfs to be ready
Feb 04 14:29:55 arch daemon[21084]: Waiting for sysfs to be ready```

**Comment by QuiiBz** [comment]
> Same problem here w/ Razer blade 15 Base 2020. The daemon is running, but looks like it can't find `sysfs`:
> 
> ```
> sudo systemctl status razerdaemon.service
> * razerdaemon.service - Razer laptop control daemon
>      Loaded: loaded (/etc/systemd/system/razerdaemon.service; enabled; vendor preset: dis>
>      Active: active (running) since Thu 2021-02-04 14:29:42 CET; 13s ago
>    Main PID: 21084 (daemon)
>       Tasks: 1 (limit: 19023)
>      Memory: 200.0K
>      CGroup: /system.slice/razerdaemon.service
>              `-21084 /usr/share/razercontrol/daemon
> 
> Feb 04 14:29:46 arch daemon[21084]: Waiting for sysfs to be ready
> Feb 04 14:29:47 arch daemon[21084]: Waiting for sysfs to be ready
> Feb 04 14:29:48 arch daemon[21084]: Waiting for sysfs to be ready
> Feb 04 14:29:49 arch daemon[21084]: Waiting for sysfs to be ready
> Feb 04 14:29:50 arch daemon[21084]: Waiting for sysfs to be ready
> Feb 04 14:29:51 arch daemon[21084]: Waiting for sysfs to be ready
> Feb 04 14:29:52 arch daemon[21084]: Waiting for sysfs to be ready
> Feb 04 14:29:53 arch daemon[21084]: Waiting for sysfs to be ready
> Feb 04 14:29:54 arch daemon[21084]: Waiting for sysfs to be ready
> Feb 04 14:29:55 arch daemon[21084]: Waiting for sysfs to be ready```
> ```

Solved by rebuilding with the latest [version](https://aur.archlinux.org/packages/razer-laptop-control-dkms-git) and rebooting the system. @phelps-sg Could you try this way?

**Comment by phelps-sg** [comment]
> > Same problem here w/ Razer blade 15 Base 2020. The daemon is running, but looks like it can't find `sysfs`:
> > ```
> > sudo systemctl status razerdaemon.service
> > * razerdaemon.service - Razer laptop control daemon
> >      Loaded: loaded (/etc/systemd/system/razerdaemon.service; enabled; vendor preset: dis>
> >      Active: active (running) since Thu 2021-02-04 14:29:42 CET; 13s ago
> >    Main PID: 21084 (daemon)
> >       Tasks: 1 (limit: 19023)
> >      Memory: 200.0K
> >      CGroup: /system.slice/razerdaemon.service
> >              `-21084 /usr/share/razercontrol/daemon
> > 
> > Feb 04 14:29:46 arch daemon[21084]: Waiting for sysfs to be ready
> > Feb 04 14:29:47 arch daemon[21084]: Waiting for sysfs to be ready
> > Feb 04 14:29:48 arch daemon[21084]: Waiting for sysfs to be ready
> > Feb 04 14:29:49 arch daemon[21084]: Waiting for sysfs to be ready
> > Feb 04 14:29:50 arch daemon[21084]: Waiting for sysfs to be ready
> > Feb 04 14:29:51 arch daemon[21084]: Waiting for sysfs to be ready
> > Feb 04 14:29:52 arch daemon[21084]: Waiting for sysfs to be ready
> > Feb 04 14:29:53 arch daemon[21084]: Waiting for sysfs to be ready
> > Feb 04 14:29:54 arch daemon[21084]: Waiting for sysfs to be ready
> > Feb 04 14:29:55 arch daemon[21084]: Waiting for sysfs to be ready```
> > ```
> 
> Solved by rebuilding with the latest [version](https://aur.archlinux.org/packages/razer-laptop-control-dkms-git) and rebooting the system. @phelps-sg Could you try this way?

I was already on latest version in main branch.  I also tried rebuilding against the v1.3.0 release, and then rebooting, but same problem.

**Comment by mike-lloyd03** [comment]
I have the same problem. Razer Blade 2020 Advanced. Running on Manjaro KDE. Daemon was installed with the Manjaro Software Update.

**Comment by phelps-sg** [comment]
Note that there appear to be two different failure modes in the above reports:
1. `Option::unwrap()` on a `None` value
2. Timed out waiting for sysfs after a minute!

As per the OP I am experiencing 1:

~~~
RUST_BACKTRACE=full /usr/share/razercontrol/daemon
Sysfs ready! Starting daemon
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/driver_sysfs.rs:21:14
stack backtrace:
   0:     0x55ec68bb593c - std::backtrace_rs::backtrace::libunwind::trace::h87bbdc8ae314e5a4
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55ec68bb593c - std::backtrace_rs::backtrace::trace_unsynchronized::h779de2081f0fe77d
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55ec68bb593c - std::sys_common::backtrace::_print_fmt::h7f9f27f2b4d4cdf1
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:79
   3:     0x55ec68bb593c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf95d19d7937b7307
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:58
   4:     0x55ec68bde93f - core::fmt::write::h31ddd5324183dd8d
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1082
   5:     0x55ec68baf327 - std::io::Write::write_fmt::h6553ae225ae21934
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/io/mod.rs:1514
   6:     0x55ec68bc93e0 - std::sys_common::backtrace::_print::h6d7cde6fb59a3272
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:61
   7:     0x55ec68bc93e0 - std::sys_common::backtrace::print::h024fb5a1f254b027
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:48
   8:     0x55ec68bc93e0 - std::panicking::default_hook::{{closure}}::h008654930ff7c19c
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:200
   9:     0x55ec68bc913e - std::panicking::default_hook::h611ef89f1ca4afb7
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:219
  10:     0x55ec68bc99c3 - std::panicking::rust_panic_with_hook::h4dfeaf97568ec250
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:569
  11:     0x55ec68bb5d79 - std::panicking::begin_panic_handler::{{closure}}::hf55586f621f9c415
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:476
  12:     0x55ec68bb5a8c - std::sys_common::backtrace::__rust_end_short_backtrace::hbddda20e4c1f6fd7
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:153
  13:     0x55ec68bc95d2 - rust_begin_unwind
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
  14:     0x55ec68bde5f1 - core::panicking::panic_fmt::he4c3f055751e8cea
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
  15:     0x55ec68bde53d - core::panicking::panic::hdb4ebd5c0dcce155
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:50
  16:     0x55ec68b85c30 - std::sync::once::Once::call_once::{{closure}}::hdab72874dd3e223c
  17:     0x55ec68bbb7b5 - std::sync::once::Once::call_inner::h2ab717bd4630065d
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sync/once.rs:421
  18:     0x55ec68b89986 - daemon::main::hbf1019e3af7e563c
  19:     0x55ec68b97633 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf7094a1450cc37c6
  20:     0x55ec68b97649 - std::rt::lang_start::{{closure}}::h82b6dafccc6059fe
  21:     0x55ec68bc9d1c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h198b3348bc6fe6ff
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/ops/function.rs:259
  22:     0x55ec68bc9d1c - std::panicking::try::do_call::hb35a1579447c1de7
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:373
  23:     0x55ec68bc9d1c - std::panicking::try::h5fe941721b9f82d8
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:337
  24:     0x55ec68bc9d1c - std::panic::catch_unwind::h5184cddbb930bb79
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panic.rs:379
  25:     0x55ec68bc9d1c - std::rt::lang_start_internal::ha12a50f31e33d94f
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/rt.rs:51
  26:     0x55ec68b8a0e2 - main
  27:     0x7fcaf14480b3 - __libc_start_main
  28:     0x55ec68b7f0ae - _start
  29:                0x0 - <unknown>
~~~

**Comment by MagicGnome-UwU** [comment]
Did someone find a fix to make it work? or has someone a different software to control Fans/RGB

**Comment by phelps-sg** [comment]
> Did someone find a fix to make it work? or has someone a different software to control Fans/RGB

I have now got it working.  The problem was incompatibility with openrazer.  I removed the following package:

~~~bash
sudo apt remove openrazer-driver-dkms
~~~

This is documented in `driver/README.md` which states:

**If you have openrazer installed, you must remove it from your system.**

**Comment by MagicGnome-UwU** [comment]
> > Did someone find a fix to make it work? or has someone a different software to control Fans/RGB
> 
> I have now got it working. The problem was incompatibility with openrazer. I removed the following package:
> 
> ```shell
> sudo apt remove openrazer-driver-dkms
> ```
> 
> This is documented in `driver/README.md` which states:
> 
> **If you have openrazer installed, you must remove it from your system.**

I didn't have openrazer installed. But still get the same issue: Error. Socket doesn't exit. Is daemon running?

**Comment by jarbus** [comment]
Same issue with base 15 2021, don't have openrazer installed

**Comment by lexizz** [comment]
Same [issue](https://github.com/rnd-ash/razer-laptop-control/issues/68) with Blade Stealth 13 (Late 2020). I haven't openrazer installed.

**Comment by theboringkid** [comment]
I fixed it by uninstalling it, and then compiling it myself (See issue #56 for a guide, it really isn't complicated, but you need to replace `sudo update-initramfs -u` with `sudo mkinitcpio` if you are running Arch (or maybe on other Distros as well, but I only know that you need to replace it in arch since I am using Arch)
